{{- $chartName := include "app.name" . -}}
{{- $releaseName := .Release.Name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-nginx-deployment
  labels:
    app: {{ $releaseName }}-{{ $chartName }}
    component: nginx-deployment
    release: {{ $releaseName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $releaseName }}-{{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-nginx
  template:
    metadata:
      labels:
        app: {{ $releaseName }}-{{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-nginx
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
      - name: {{ $releaseName }}-nginx
        image: "{{ .Values.image.registryUrl }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
