{{- $releaseName := .Release.Name -}}
{{- $chartName := include "app.name" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ $releaseName }}-{{ $chartName }}
    component: nginx-service
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
      app: {{ $releaseName }}-{{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-nginx
