apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:    
  project: devops-testing
  source:
    repoURL: acrarolibotnonprod.azurecr.io
    targetRevision: 1.1.0
    helm:
      parameters:
        - name: authorization.domain
          value: raster
        - name: cloudProvider.dockerRegistryUrl
          value: acrarolibotnonprod.azurecr.io
        - name: cloudProvider.imagePullSecretName
          value: acr-registry
        - name: authorization.url
          value: 'http://opa-la-opa-service.integration/v1/data/http/authz/decision'
        - name: image.repository
          value: nginx-otel-unprivileged
        - name: image.tag
          value: v1.0.0
      fileParameters:
      - name: nginx.tls.certificate
        path: config/ca.crt
    chart: helm/nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops-testing
