# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registryUrl: "registry"
  repository: "repo-name"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  pullSecret: pullsecretname

service:
  type: ClusterIP
  port: 8080
